name: Gravity
version: ${project.version}
main: com.flareman99.minigame.Main
api-version: 1.16
commands:
    maps:
      description: list all maps for Gravity
      aliases: []
    activemaps:
      description: list all active maps for Gravity
      aliases: []