lobby:
  location: "1067.5 177 350.5"
  facing: "EAST"
  time: 2.0
maps:
  Busy-Bees:
    spawn: "0.5 246 -0.5"
    facing: "SOUTH"
    portals:
      1:
        - "29 1 -4"
        - "29 4 0"
      2:
        - "4 18 1"
        - "9 21 1"
      3:
        - "9 21 1"
        - "9 18 6"
  The-Hive:
    spawn:  "9.5 250 350.5"
    facing: "WEST"
    portals:
      1:
        - "1 4 338"
        - "5 7 338"
  The-Crib:
    spawn: "354.5 240 350"
    facing: "WEST"
    portals:
      1:
        - "368 26 348"
        - "368 30 351"
  Dragons-Keep:
    spawn: "-350.5 241 6.5"
    facing: "NORTH"
    portals:
      1:
        - "-356 22 -20"
        - "-346 31 -20"
  Pacman:
    spawn: "-348.5 249 -345.5"
    facing: "NORTH"
    portals:
      1:
        - "-341 6 -352"
        - "-340 8 -348"
      2:
        - "-358 6 -348"
        - "-358 9 -351"
  Starfighter:
    spawn: "347.5 245 -349.5"
    facing: "EAST"
    portals:
      1:
        - "352 63 -320"
        - "348 65 -320"
  Tekashi69:
    spawn: "-351.5 247 347.5"
    facing: "NORTH"
    portals:
      1:
        - "-371 3 358"
        - "-376 5 358"
  Tron:
    spawn: "-1049.5 244 -2.5"
    facing: "SOUTH"
    portals:
      1:
        - "-1048 60 15"
        - "-1052 62 15"
  Onion-Rings:
    spawn: "-1051.5 231 339"
    facing: "SOUTH"
    portals:
      1:
        - "-1049 13 355"
        - "-1055 15 355"
      2:
        - "-1065 13 345"
        - "-1065 16 340"
      3:
        - "-1039 13 339"
        - "-1039 16 344"
      4:
        - "-1055 13 329"
        - "-1050 16 329"
  Sea-World:
    spawn: "-1049.5 246 698.5"
    facing: "SOUTH"
    portals:
      1:
        - "-1071 25 700"
        - "-1071 28 697"
      2:
        - "-1054 25 679"
        - "-1051 28 679"
      3:
        - "-1033 25 697"
        - "-1033 27 701"
      4:
        - "-1050 25 717"
        - "-1053 28 717"

  Arachnophobia:
    spawn: "-1034.5 233 994.5"
    facing: "SOUTH"
    portals:
      1:
        - "-1005 5 993"
        - "-1005 9 999"
  Johnny-Johnny:
    spawn: "-1049.5 247 -346.5"
    facing: "NORTH"
    portals:
      1:
        - "-1052 7 -360"
        - "-1048 9 -360"
  Cerro-Gordo:
    spawn: "-1049.5 245 -702.5"
    facing: "SOUTH"
    portals:
      1:
        - "-1039 50 -745"
        - "-1035 52 -745"
      2:
        - "-1055 83 -716"
        - "-1051 87 -716"
  Tomb:
    spawn: "-352.5 246 -699.5"
    facing: "EAST"
    portals:
      1:
        - "-338 41 -702"
        - "-338 43 -697"
  Kindergarten:
    spawn: "1048.5 248 -300.5"
    facing: "EAST"
    portals:
      1:
        - "1081 5 -303"
        - "1081 8 -300"
      2:
        - "1052 5 -270"
        - "1049 8 -270"
      3:
        - "1019 5 -299"
        - "1019 7 -302"
      4:
        - "1048 5 -332"
        - "1051 8 -332"

  Airborne:
    spawn: "1048.5 245 -699.5"
    facing: "EAST"
    portals:
      1:
        - "1026 2 -724"
        - "1031 4 -724"
  Sanic:
    spawn: "-351.5 244 -1045.5"
    facing: "NORTH"
    portals:
      1:
        - "-354 81 -1063"
        - "-348 88 -1063"
  Armageddon:
    spawn: "-699.5 253 -1054.5"
    facing: "SOUTH"
    portals:
      1:
        - "-715 7 -1049"
        - "-715 12 -1055"
  Bullseye:
    spawn: "0.5 245 -355"
    facing: "SOUTH"
    portals:
      1:
        - "-20 20 -346"
        - "-25 24 -346"
      2:
        - "2 20 -370"
        - "2 24 -375"
      3:
        - "26 21 -359"
        - "31 25 -359"
      4:
        - "3 27 -322"
        - "3 23 -327"
  Birdhouse:
    spawn: "702 248 5.5"
    facing: "NORTH"
    portals:
      1:
        - "674 3 0"
        - "674 6 -8"
  Warwick-Castle:
    spawn: "-704.5 249 0.5"
    facing: "EAST"
    portals:
      1:
        - "-700 10 2"
        - "-700 7 -2"
  Space-Run:
    spawn: "-47 248 748"
    facing: "SOUTH"
    portals:
      1:
        - "-49 13 728"
        - "-45 10 728"
  Minecart-Express:
    spawn: "-1.55 253 -697.6"
    facing: "NORTH"
    portals:
      1:
        - "1 16 -680"
        - "-3 18 -680"
  Uber:
    spawn: "698 228 705"
    facing: "NORTH"
    portals:
      1:
        - "696 17 687"
        - "700 13 687"
  Aether:
    spawn: "-695 243 700.5"
    facing: "WEST"
    portals:
      1:
        - "-713 24 703"
        - "-713 18 697"
  Sewage:
    spawn: "-694.5 251 -700"
    facing: "WEST"
    portals:
      1:
        - "-700 13 -714"
        - "-696 9 -714"
  Yeti:
    spawn: "756 244 -657"
    facing: "SOUTH"
    portals:
      1:
        - "758 9 -649"
        - "754 5 -649"
  Swervin:
    spawn: "328.7 247 2.5"
    facing: "WEST"
    portals:
      1:
        - "319 12 13"
        - "315 10 13"
  Ambush:
    spawn: "-68 250 1039"
    facing: "SOUTH"
    portals:
      1:
        - "-63 12 1063"
        - "-67 8 1063"
  Matrix:
    spawn: "-340.5 250 1029"
    facing: "SOUTH"
    portals:
      1:
        - "-308 5 1012"
        - "-312 3 1012"
  Battle-Box:
    spawn: "846 247 1064"
    facing: "EAST"
    portals:
      1:
        - "890 14 1062"
        - "890 11 1067"
